
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Sim_Div = 9;
  public static final int Sim_ParA = 4;
  public static final int UMINUS = 12;
  public static final int TK_Doble = 11;
  public static final int TK_Entero = 10;
  public static final int Sim_PyC = 3;
  public static final int EOF = 0;
  public static final int Sim_Menos = 7;
  public static final int Res_Operar = 2;
  public static final int error = 1;
  public static final int Sim_Por = 8;
  public static final int Sim_Mas = 6;
  public static final int Sim_ParC = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Res_Operar",
  "Sim_PyC",
  "Sim_ParA",
  "Sim_ParC",
  "Sim_Mas",
  "Sim_Menos",
  "Sim_Por",
  "Sim_Div",
  "TK_Entero",
  "TK_Doble",
  "UMINUS"
  };
}

